# Redis

# Login and connection information for the Redis server
RedisServer:
  URL: localhost
  Port: 6379
  Password: pass


# Name of the BungeeCord instance.
BungeeName: Bungee

# Exact name of the server as listed in the BungeeCord config (Case-Sensitive !).
# This name is case-sensitive! Please double check to make sure it is correct.
ServerNameInBungeeCord: World

# Time in ticks for every online server and online player update
OnlineUpdatePeriod: 300

# Debug var
DebugMode: True
